Repository Domi-do/Domido-Backend, pull requests merged in 2025-06, with the labels that each got.

#3 [FEATURE]: MongoDB 연결 및 도미노 조회 API(GET /) 구현
  Models/DominosSchema.js
  config/db.js
  constants/index.js
  index.js
  package-lock.json
  package.json
  routes/dominos.js
Labels: BE, config

#7 Feature: 로그인 기능 구현 (카카오 OAuth)
  Models/UserInfoSchema.js
  index.js
  package-lock.json
  package.json
  routes/user.js
  utills/utills.js
Labels: BE

#10 Feature: 리프레시 토큰을 이용한 액세스 토큰 재발급 API 구현
  index.js
  routes/projects.js
  routes/user.js
  utills/utills.js
Labels: BE

#12 Refactor: 도미노 CRUD 통합 및 모델/스키마 책임 분리
  Models/DominosSchema.js
  Models/ObjectInfoSchema.js
  Models/ProjectSchema.js
  routes/dominos.js
  routes/projects.js
Labels: BE

#17 Fix: 일부 오브젝트가 씬에 배치되지 않는 현상 수정
  Models/ObjectInfoSchema.js
  constants/index.js
Labels: bug

#19 Feature: 리프레시 토큰을 이용한 액세스 토큰 재발급 API 구현
  Models/UserInfoSchema.js
  index.js
  package-lock.json
  package.json
  routes/user.js
Labels: BE

#15 Feature: 로그인 권한 검증 미들웨어 구현
  index.js
  middlewares/authMiddleware.js
  routes/dominos.js
  routes/projects.js
  utills/utills.js
Labels: BE

#18 [FEATURE] 멀티플레이 소켓 로직 구현 및 사용자 식별 기능 추가
  config/socket.js
  constants/index.js
  index.js
  package-lock.json
  package.json
  routes/user.js
Labels: enhancement, BE

#21 Feat: 도미노 동기화 버그 수정 및 방 제어 기능 개선
  config/socket.js
  index.js
Labels: enhancement, BE

#27 Fix: MongoDB 도큐먼트 저장 시 동일한 _id가 중복 생성되는 현상 수정
  Models/ObjectInfoSchema.js
  constants/index.js
  routes/dominos.js
Labels: bug

#28 Refactor: JWT 만료 시간 연장 및 요청 body 크기 제한 확장
  index.js
  utills/utills.js
Labels: bug, BE

#29 Feature: 레인보우 슬라이드 오브젝트 추가
  constants/index.js
Labels: BE

#31 Feat: 도미노 업데이트 socket 전파 시 sendUser(userID) 정보 포함
  config/socket.js
Labels: bug, BE

#35 Refactor: io.to → socket.to로 변경하여 방 내부 이벤트 브로드캐스트 방식 적용
  config/socket.js
Labels: BE

#40 Feature: 업적 달성 기능 구현을 위한 achievement route 추가
  .gitignore
  Models/AchievementSchema.js
  index.js
  routes/achievements.js
Labels: BE

#42 Fix: 리셋 시 도미노 중복/삭제 오류 해결을 위한 전체 덮어쓰기 API 도입
  config/socket.js
  routes/dominos.js
Labels: bug

#46 Refactor: 도미노 업적 라우트 로직 수정
  Models/AchievementSchema.js
  Models/UserInfoSchema.js
  routes/achievements.js
Labels: BE

#48 Feature: 회원가입시 프리셋 프로젝트 생성
  constants/presetDominos.js
  routes/projects.js
  routes/user.js
  utills/utills.js
Labels: BE
